host: www.scscfw.com #aaaa
port: 389
base:
  base: dc=scscfw,dc=com
  person: ou=people,dc=scscfw,dc=com
attr:
  - displayName
  - uid
  - sn
  - cn
  - mail
  - mobile
  - userPassword
objectclass:
  - inetOrgPerson
  - organizationalPerson
  - top
  - person
bind:
  dn: cn=admin,dc=scscfw,dc=com
  passwd: ts3qdf
