development:
  sessions:
    default:
      database: member_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: member_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
