# config/settings.yml
defaults: &defaults
  # 域名配置
  site_host: 'http://www.scscfw.con:90'
  # 重置密码配置
  password_reset:
    # 过期时间
    expire_time: 3600
  #邮件配置
  smtp:
    username: 'scrxcscfww@163.com'
    password: 'cscrxckjyxgs'
    port: 25
    address: 'smtp.163.com'
    nickname: '四川省服务中心'
    authentication: 'login'
    helo_domain: 'scscfw.com'
  register_redirect: 'http://www.scscfw.com'
  home_page_url: "http://www.scscfw.com:90"
  admin_user: "administrator,yinchangxin"
  user_home_page_url: "http://www.scscfw.com"
  no_permission: "对不起，您没有操作该功能的权限。"
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
